/* Palteca lesson content — generated + native-speaker-verified for ES/FR/ZH. 58 items/language across 7 themes. */
window.PALTECA_CONTENT = {
  "themes": [
    {
      "id": "greetings",
      "title": "Greetings & Courtesy",
      "icon": "👋"
    },
    {
      "id": "numbers",
      "title": "Numbers 1–10",
      "icon": "🔢"
    },
    {
      "id": "food",
      "title": "Food & Drink",
      "icon": "🍽️"
    },
    {
      "id": "family",
      "title": "Family & People",
      "icon": "👪"
    },
    {
      "id": "colors",
      "title": "Colors",
      "icon": "🎨"
    },
    {
      "id": "travel",
      "title": "Travel & Directions",
      "icon": "✈️"
    },
    {
      "id": "phrases",
      "title": "Everyday Phrases",
      "icon": "💬"
    }
  ],
  "languages": {
    "es": {
      "language": "Spanish",
      "code": "es",
      "bcp47": "es-ES",
      "flag": "🇪🇸",
      "native": "Español",
      "items": [
        {
          "id": "hello",
          "theme": "greetings",
          "target": "Hola",
          "translation": "Hello",
          "phonetic": "OH-lah",
          "emoji": "👋",
          "example": "¡Hola! ¿Qué tal?",
          "exampleTranslation": "Hello! How's it going?",
          "article": ""
        },
        {
          "id": "goodbye",
          "theme": "greetings",
          "target": "Adiós",
          "translation": "Goodbye",
          "phonetic": "ah-DYOHS",
          "emoji": "👋",
          "example": "Adiós, hasta mañana.",
          "exampleTranslation": "Goodbye, see you tomorrow.",
          "article": ""
        },
        {
          "id": "good_morning",
          "theme": "greetings",
          "target": "Buenos días",
          "translation": "Good morning",
          "phonetic": "BWEH-nohs DEE-ahs",
          "emoji": "🌅",
          "example": "Buenos días, ¿cómo amaneció?",
          "exampleTranslation": "Good morning, how did you wake up?",
          "article": ""
        },
        {
          "id": "please",
          "theme": "greetings",
          "target": "Por favor",
          "translation": "Please",
          "phonetic": "por fah-VOR",
          "emoji": "🙏",
          "example": "Un café, por favor.",
          "exampleTranslation": "A coffee, please.",
          "article": ""
        },
        {
          "id": "thank_you",
          "theme": "greetings",
          "target": "Gracias",
          "translation": "Thank you",
          "phonetic": "GRAH-syahs",
          "emoji": "🙏",
          "example": "Muchas gracias por tu ayuda.",
          "exampleTranslation": "Thank you very much for your help.",
          "article": ""
        },
        {
          "id": "yes",
          "theme": "greetings",
          "target": "Sí",
          "translation": "Yes",
          "phonetic": "SEE",
          "emoji": "✅",
          "example": "Sí, me gusta mucho.",
          "exampleTranslation": "Yes, I like it a lot.",
          "article": ""
        },
        {
          "id": "no",
          "theme": "greetings",
          "target": "No",
          "translation": "No",
          "phonetic": "NOH",
          "emoji": "🚫",
          "example": "No, gracias.",
          "exampleTranslation": "No, thank you.",
          "article": ""
        },
        {
          "id": "excuse_me",
          "theme": "greetings",
          "target": "Perdón",
          "translation": "Excuse me",
          "phonetic": "per-DOHN",
          "emoji": "🙋",
          "example": "Perdón, ¿puedo pasar?",
          "exampleTranslation": "Excuse me, may I get through?",
          "article": ""
        },
        {
          "id": "one",
          "theme": "numbers",
          "target": "Uno",
          "translation": "One",
          "phonetic": "OO-noh",
          "emoji": "1️⃣",
          "example": "Solo quiero uno.",
          "exampleTranslation": "I only want one.",
          "article": ""
        },
        {
          "id": "two",
          "theme": "numbers",
          "target": "Dos",
          "translation": "Two",
          "phonetic": "DOHS",
          "emoji": "2️⃣",
          "example": "Tengo dos hermanos.",
          "exampleTranslation": "I have two brothers.",
          "article": ""
        },
        {
          "id": "three",
          "theme": "numbers",
          "target": "Tres",
          "translation": "Three",
          "phonetic": "TREHS",
          "emoji": "3️⃣",
          "example": "Son las tres de la tarde.",
          "exampleTranslation": "It's three in the afternoon.",
          "article": ""
        },
        {
          "id": "four",
          "theme": "numbers",
          "target": "Cuatro",
          "translation": "Four",
          "phonetic": "KWAH-troh",
          "emoji": "4️⃣",
          "example": "Hay cuatro sillas.",
          "exampleTranslation": "There are four chairs.",
          "article": ""
        },
        {
          "id": "five",
          "theme": "numbers",
          "target": "Cinco",
          "translation": "Five",
          "phonetic": "SEEN-koh",
          "emoji": "5️⃣",
          "example": "Tengo cinco euros.",
          "exampleTranslation": "I have five euros.",
          "article": ""
        },
        {
          "id": "six",
          "theme": "numbers",
          "target": "Seis",
          "translation": "Six",
          "phonetic": "SAYSS",
          "emoji": "6️⃣",
          "example": "El tren sale a las seis.",
          "exampleTranslation": "The train leaves at six.",
          "article": ""
        },
        {
          "id": "seven",
          "theme": "numbers",
          "target": "Siete",
          "translation": "Seven",
          "phonetic": "SYEH-teh",
          "emoji": "7️⃣",
          "example": "La semana tiene siete días.",
          "exampleTranslation": "The week has seven days.",
          "article": ""
        },
        {
          "id": "eight",
          "theme": "numbers",
          "target": "Ocho",
          "translation": "Eight",
          "phonetic": "OH-choh",
          "emoji": "8️⃣",
          "example": "Nos vemos a las ocho.",
          "exampleTranslation": "We'll meet at eight.",
          "article": ""
        },
        {
          "id": "nine",
          "theme": "numbers",
          "target": "Nueve",
          "translation": "Nine",
          "phonetic": "NWEH-beh",
          "emoji": "9️⃣",
          "example": "Mi hijo tiene nueve años.",
          "exampleTranslation": "My son is nine years old.",
          "article": ""
        },
        {
          "id": "ten",
          "theme": "numbers",
          "target": "Diez",
          "translation": "Ten",
          "phonetic": "DYEHS",
          "emoji": "🔟",
          "example": "Cuesta diez euros.",
          "exampleTranslation": "It costs ten euros.",
          "article": ""
        },
        {
          "id": "water",
          "theme": "food",
          "target": "Agua",
          "translation": "Water",
          "phonetic": "AH-gwah",
          "emoji": "💧",
          "example": "¿Me trae un vaso de agua?",
          "exampleTranslation": "Could you bring me a glass of water?",
          "article": "el"
        },
        {
          "id": "coffee",
          "theme": "food",
          "target": "Café",
          "translation": "Coffee",
          "phonetic": "kah-FEH",
          "emoji": "☕",
          "example": "Me gusta el café con leche.",
          "exampleTranslation": "I like coffee with milk.",
          "article": "el"
        },
        {
          "id": "bread",
          "theme": "food",
          "target": "Pan",
          "translation": "Bread",
          "phonetic": "PAHN",
          "emoji": "🍞",
          "example": "El pan está muy fresco.",
          "exampleTranslation": "The bread is very fresh.",
          "article": "el"
        },
        {
          "id": "apple",
          "theme": "food",
          "target": "Manzana",
          "translation": "Apple",
          "phonetic": "mahn-SAH-nah",
          "emoji": "🍎",
          "example": "Como una manzana cada día.",
          "exampleTranslation": "I eat an apple every day.",
          "article": "la"
        },
        {
          "id": "chicken",
          "theme": "food",
          "target": "Pollo",
          "translation": "Chicken",
          "phonetic": "POH-yoh",
          "emoji": "🍗",
          "example": "El pollo está delicioso.",
          "exampleTranslation": "The chicken is delicious.",
          "article": "el"
        },
        {
          "id": "rice",
          "theme": "food",
          "target": "Arroz",
          "translation": "Rice",
          "phonetic": "ah-RROHS",
          "emoji": "🍚",
          "example": "Quiero arroz con pollo.",
          "exampleTranslation": "I want rice with chicken.",
          "article": "el"
        },
        {
          "id": "tea",
          "theme": "food",
          "target": "Té",
          "translation": "Tea",
          "phonetic": "TEH",
          "emoji": "🍵",
          "example": "Prefiero un té caliente.",
          "exampleTranslation": "I prefer a hot tea.",
          "article": "el"
        },
        {
          "id": "the_bill",
          "theme": "food",
          "target": "La cuenta",
          "translation": "The bill / check",
          "phonetic": "lah KWEHN-tah",
          "emoji": "🧾",
          "example": "La cuenta, por favor.",
          "exampleTranslation": "The check, please.",
          "article": "la"
        },
        {
          "id": "mother",
          "theme": "family",
          "target": "Madre",
          "translation": "Mother",
          "phonetic": "MAH-dreh",
          "emoji": "👩",
          "example": "Mi madre cocina muy bien.",
          "exampleTranslation": "My mother cooks very well.",
          "article": "la"
        },
        {
          "id": "father",
          "theme": "family",
          "target": "Padre",
          "translation": "Father",
          "phonetic": "PAH-dreh",
          "emoji": "👨",
          "example": "Mi padre trabaja mucho.",
          "exampleTranslation": "My father works a lot.",
          "article": "el"
        },
        {
          "id": "friend",
          "theme": "family",
          "target": "Amigo",
          "translation": "Friend",
          "phonetic": "ah-MEE-goh",
          "emoji": "🤝",
          "example": "Él es mi mejor amigo.",
          "exampleTranslation": "He is my best friend.",
          "article": "el"
        },
        {
          "id": "child",
          "theme": "family",
          "target": "Niño",
          "translation": "Child",
          "phonetic": "NEE-nyoh",
          "emoji": "🧒",
          "example": "El niño juega en el parque.",
          "exampleTranslation": "The child plays in the park.",
          "article": "el"
        },
        {
          "id": "man",
          "theme": "family",
          "target": "Hombre",
          "translation": "Man",
          "phonetic": "OHM-breh",
          "emoji": "👨",
          "example": "Ese hombre es muy amable.",
          "exampleTranslation": "That man is very kind.",
          "article": "el"
        },
        {
          "id": "woman",
          "theme": "family",
          "target": "Mujer",
          "translation": "Woman",
          "phonetic": "moo-HEHR",
          "emoji": "👩",
          "example": "Esa mujer es doctora.",
          "exampleTranslation": "That woman is a doctor.",
          "article": "la"
        },
        {
          "id": "brother",
          "theme": "family",
          "target": "Hermano",
          "translation": "Brother",
          "phonetic": "er-MAH-noh",
          "emoji": "👦",
          "example": "Mi hermano estudia inglés.",
          "exampleTranslation": "My brother studies English.",
          "article": "el"
        },
        {
          "id": "sister",
          "theme": "family",
          "target": "Hermana",
          "translation": "Sister",
          "phonetic": "er-MAH-nah",
          "emoji": "👧",
          "example": "Mi hermana vive en Madrid.",
          "exampleTranslation": "My sister lives in Madrid.",
          "article": "la"
        },
        {
          "id": "red",
          "theme": "colors",
          "target": "Rojo",
          "translation": "Red",
          "phonetic": "ROH-hoh",
          "emoji": "🔴",
          "example": "Me gusta el coche rojo.",
          "exampleTranslation": "I like the red car.",
          "article": ""
        },
        {
          "id": "blue",
          "theme": "colors",
          "target": "Azul",
          "translation": "Blue",
          "phonetic": "ah-SOOL",
          "emoji": "🔵",
          "example": "El cielo es azul.",
          "exampleTranslation": "The sky is blue.",
          "article": ""
        },
        {
          "id": "green",
          "theme": "colors",
          "target": "Verde",
          "translation": "Green",
          "phonetic": "BEHR-deh",
          "emoji": "🟢",
          "example": "La hierba es verde.",
          "exampleTranslation": "The grass is green.",
          "article": ""
        },
        {
          "id": "yellow",
          "theme": "colors",
          "target": "Amarillo",
          "translation": "Yellow",
          "phonetic": "ah-mah-REE-yoh",
          "emoji": "🟡",
          "example": "El sol es amarillo.",
          "exampleTranslation": "The sun is yellow.",
          "article": ""
        },
        {
          "id": "black",
          "theme": "colors",
          "target": "Negro",
          "translation": "Black",
          "phonetic": "NEH-groh",
          "emoji": "⚫",
          "example": "Llevo un abrigo negro.",
          "exampleTranslation": "I'm wearing a black coat.",
          "article": ""
        },
        {
          "id": "white",
          "theme": "colors",
          "target": "Blanco",
          "translation": "White",
          "phonetic": "BLAHN-koh",
          "emoji": "⚪",
          "example": "La nieve es blanca.",
          "exampleTranslation": "The snow is white.",
          "article": ""
        },
        {
          "id": "orange",
          "theme": "colors",
          "target": "Naranja",
          "translation": "Orange",
          "phonetic": "nah-RAHN-hah",
          "emoji": "🟠",
          "example": "Su camiseta es naranja.",
          "exampleTranslation": "His shirt is orange.",
          "article": ""
        },
        {
          "id": "purple",
          "theme": "colors",
          "target": "Morado",
          "translation": "Purple",
          "phonetic": "moh-RAH-doh",
          "emoji": "🟣",
          "example": "Las flores son moradas.",
          "exampleTranslation": "The flowers are purple.",
          "article": ""
        },
        {
          "id": "airport",
          "theme": "travel",
          "target": "Aeropuerto",
          "translation": "Airport",
          "phonetic": "ah-eh-roh-PWEHR-toh",
          "emoji": "✈️",
          "example": "Vamos al aeropuerto en taxi.",
          "exampleTranslation": "We're going to the airport by taxi.",
          "article": "el"
        },
        {
          "id": "hotel",
          "theme": "travel",
          "target": "Hotel",
          "translation": "Hotel",
          "phonetic": "oh-TEHL",
          "emoji": "🏨",
          "example": "El hotel está cerca de la playa.",
          "exampleTranslation": "The hotel is near the beach.",
          "article": "el"
        },
        {
          "id": "left",
          "theme": "travel",
          "target": "Izquierda",
          "translation": "Left",
          "phonetic": "ees-KYEHR-dah",
          "emoji": "⬅️",
          "example": "Gira a la izquierda.",
          "exampleTranslation": "Turn to the left.",
          "article": "la"
        },
        {
          "id": "right",
          "theme": "travel",
          "target": "Derecha",
          "translation": "Right",
          "phonetic": "deh-REH-chah",
          "emoji": "➡️",
          "example": "El baño está a la derecha.",
          "exampleTranslation": "The bathroom is on the right.",
          "article": "la"
        },
        {
          "id": "ticket",
          "theme": "travel",
          "target": "Billete",
          "translation": "Ticket",
          "phonetic": "bee-YEH-teh",
          "emoji": "🎫",
          "example": "Necesito un billete de tren.",
          "exampleTranslation": "I need a train ticket.",
          "article": "el"
        },
        {
          "id": "train",
          "theme": "travel",
          "target": "Tren",
          "translation": "Train",
          "phonetic": "TREHN",
          "emoji": "🚆",
          "example": "El tren llega a las nueve.",
          "exampleTranslation": "The train arrives at nine.",
          "article": "el"
        },
        {
          "id": "where_is",
          "theme": "travel",
          "target": "¿Dónde está...?",
          "translation": "Where is...?",
          "phonetic": "DOHN-deh ehs-TAH",
          "emoji": "❓",
          "example": "¿Dónde está la estación?",
          "exampleTranslation": "Where is the station?",
          "article": ""
        },
        {
          "id": "help",
          "theme": "travel",
          "target": "¡Ayuda!",
          "translation": "Help!",
          "phonetic": "ah-YOO-dah",
          "emoji": "🆘",
          "example": "¡Ayuda, por favor!",
          "exampleTranslation": "Help, please!",
          "article": ""
        },
        {
          "id": "how_are_you",
          "theme": "phrases",
          "target": "¿Cómo estás?",
          "translation": "How are you?",
          "phonetic": "KOH-moh ehs-TAHS",
          "emoji": "😊",
          "example": "Hola, ¿cómo estás?",
          "exampleTranslation": "Hi, how are you?",
          "article": ""
        },
        {
          "id": "my_name_is",
          "theme": "phrases",
          "target": "Me llamo...",
          "translation": "My name is...",
          "phonetic": "meh YAH-moh",
          "emoji": "📛",
          "example": "Hola, me llamo Ana.",
          "exampleTranslation": "Hi, my name is Ana.",
          "article": ""
        },
        {
          "id": "i_dont_understand",
          "theme": "phrases",
          "target": "No entiendo",
          "translation": "I don't understand",
          "phonetic": "noh ehn-TYEHN-doh",
          "emoji": "😕",
          "example": "Lo siento, no entiendo.",
          "exampleTranslation": "Sorry, I don't understand.",
          "article": ""
        },
        {
          "id": "how_much",
          "theme": "phrases",
          "target": "¿Cuánto cuesta?",
          "translation": "How much is it?",
          "phonetic": "KWAHN-toh KWEHS-tah",
          "emoji": "💰",
          "example": "¿Cuánto cuesta este libro?",
          "exampleTranslation": "How much is this book?",
          "article": ""
        },
        {
          "id": "where_bathroom",
          "theme": "phrases",
          "target": "¿Dónde está el baño?",
          "translation": "Where is the bathroom?",
          "phonetic": "DOHN-deh ehs-TAH ehl BAH-nyoh",
          "emoji": "🚻",
          "example": "Perdón, ¿dónde está el baño?",
          "exampleTranslation": "Excuse me, where is the bathroom?",
          "article": ""
        },
        {
          "id": "i_would_like",
          "theme": "phrases",
          "target": "Quisiera...",
          "translation": "I would like...",
          "phonetic": "kee-SYEH-rah",
          "emoji": "🙋",
          "example": "Quisiera un café, por favor.",
          "exampleTranslation": "I would like a coffee, please.",
          "article": ""
        },
        {
          "id": "see_you_later",
          "theme": "phrases",
          "target": "Hasta luego",
          "translation": "See you later",
          "phonetic": "AHS-tah LWEH-goh",
          "emoji": "👋",
          "example": "Nos vemos, ¡hasta luego!",
          "exampleTranslation": "See you, see you later!",
          "article": ""
        },
        {
          "id": "cheers",
          "theme": "phrases",
          "target": "¡Salud!",
          "translation": "Cheers!",
          "phonetic": "sah-LOOD",
          "emoji": "🥂",
          "example": "¡Salud por los amigos!",
          "exampleTranslation": "Cheers to friends!",
          "article": ""
        }
      ]
    },
    "fr": {
      "language": "French",
      "code": "fr",
      "bcp47": "fr-FR",
      "flag": "🇫🇷",
      "native": "Français",
      "items": [
        {
          "id": "hello",
          "theme": "greetings",
          "target": "Bonjour",
          "translation": "Hello",
          "phonetic": "bohn-ZHOOR",
          "emoji": "👋",
          "example": "Bonjour, comment ça va ?",
          "exampleTranslation": "Hello, how are you?",
          "article": ""
        },
        {
          "id": "goodbye",
          "theme": "greetings",
          "target": "Au revoir",
          "translation": "Goodbye",
          "phonetic": "oh ruh-VWAHR",
          "emoji": "👋",
          "example": "Au revoir, à demain !",
          "exampleTranslation": "Goodbye, see you tomorrow!",
          "article": ""
        },
        {
          "id": "good_morning",
          "theme": "greetings",
          "target": "Bonjour",
          "translation": "Good morning",
          "phonetic": "bohn-ZHOOR",
          "emoji": "🌅",
          "example": "Bonjour, tu as bien dormi ?",
          "exampleTranslation": "Good morning, did you sleep well?",
          "article": "",
          "note": "French uses 'Bonjour' for both 'hello' and 'good morning'."
        },
        {
          "id": "please",
          "theme": "greetings",
          "target": "S'il vous plaît",
          "translation": "Please",
          "phonetic": "seel voo PLEH",
          "emoji": "🙏",
          "example": "Un café, s'il vous plaît.",
          "exampleTranslation": "A coffee, please.",
          "article": "",
          "note": "Informal version: 's'il te plaît'."
        },
        {
          "id": "thank_you",
          "theme": "greetings",
          "target": "Merci",
          "translation": "Thank you",
          "phonetic": "mehr-SEE",
          "emoji": "🙏",
          "example": "Merci beaucoup !",
          "exampleTranslation": "Thank you very much!",
          "article": ""
        },
        {
          "id": "yes",
          "theme": "greetings",
          "target": "Oui",
          "translation": "Yes",
          "phonetic": "WEE",
          "emoji": "✅",
          "example": "Oui, je suis d'accord.",
          "exampleTranslation": "Yes, I agree.",
          "article": ""
        },
        {
          "id": "no",
          "theme": "greetings",
          "target": "Non",
          "translation": "No",
          "phonetic": "NOHN",
          "emoji": "🚫",
          "example": "Non, merci.",
          "exampleTranslation": "No, thank you.",
          "article": ""
        },
        {
          "id": "excuse_me",
          "theme": "greetings",
          "target": "Excusez-moi",
          "translation": "Excuse me",
          "phonetic": "eks-kew-zay-MWAH",
          "emoji": "🙋",
          "example": "Excusez-moi, où est la gare ?",
          "exampleTranslation": "Excuse me, where is the station?",
          "article": ""
        },
        {
          "id": "one",
          "theme": "numbers",
          "target": "un",
          "translation": "One",
          "phonetic": "UHN",
          "emoji": "1️⃣",
          "example": "J'ai un chien.",
          "exampleTranslation": "I have one dog.",
          "article": "",
          "note": "Feminine form: 'une'."
        },
        {
          "id": "two",
          "theme": "numbers",
          "target": "deux",
          "translation": "Two",
          "phonetic": "DUH",
          "emoji": "2️⃣",
          "example": "J'ai deux frères.",
          "exampleTranslation": "I have two brothers.",
          "article": ""
        },
        {
          "id": "three",
          "theme": "numbers",
          "target": "trois",
          "translation": "Three",
          "phonetic": "TRWAH",
          "emoji": "3️⃣",
          "example": "Il est trois heures.",
          "exampleTranslation": "It is three o'clock.",
          "article": ""
        },
        {
          "id": "four",
          "theme": "numbers",
          "target": "quatre",
          "translation": "Four",
          "phonetic": "KATR",
          "emoji": "4️⃣",
          "example": "Nous sommes quatre.",
          "exampleTranslation": "There are four of us.",
          "article": ""
        },
        {
          "id": "five",
          "theme": "numbers",
          "target": "cinq",
          "translation": "Five",
          "phonetic": "SANK",
          "emoji": "5️⃣",
          "example": "Il y a cinq pommes.",
          "exampleTranslation": "There are five apples.",
          "article": ""
        },
        {
          "id": "six",
          "theme": "numbers",
          "target": "six",
          "translation": "Six",
          "phonetic": "SEESS",
          "emoji": "6️⃣",
          "example": "Il est six heures.",
          "exampleTranslation": "It is six o'clock.",
          "article": "",
          "note": "Final 's' silent before a consonant: 'six pommes' = 'see pom'."
        },
        {
          "id": "seven",
          "theme": "numbers",
          "target": "sept",
          "translation": "Seven",
          "phonetic": "SET",
          "emoji": "7️⃣",
          "example": "La semaine a sept jours.",
          "exampleTranslation": "The week has seven days.",
          "article": ""
        },
        {
          "id": "eight",
          "theme": "numbers",
          "target": "huit",
          "translation": "Eight",
          "phonetic": "WEET",
          "emoji": "8️⃣",
          "example": "Le train part à huit heures.",
          "exampleTranslation": "The train leaves at eight o'clock.",
          "article": ""
        },
        {
          "id": "nine",
          "theme": "numbers",
          "target": "neuf",
          "translation": "Nine",
          "phonetic": "NUHF",
          "emoji": "9️⃣",
          "example": "Il y a neuf joueurs.",
          "exampleTranslation": "There are nine players.",
          "article": ""
        },
        {
          "id": "ten",
          "theme": "numbers",
          "target": "dix",
          "translation": "Ten",
          "phonetic": "DEESS",
          "emoji": "🔟",
          "example": "J'ai dix euros.",
          "exampleTranslation": "I have ten euros.",
          "article": "",
          "note": "Final 's' silent before a consonant: 'dix jours' = 'dee zhoor'."
        },
        {
          "id": "water",
          "theme": "food",
          "target": "eau",
          "translation": "Water",
          "phonetic": "OH",
          "emoji": "💧",
          "example": "Je voudrais de l'eau, s'il vous plaît.",
          "exampleTranslation": "I would like some water, please.",
          "article": "l'",
          "note": "Feminine: l'eau."
        },
        {
          "id": "coffee",
          "theme": "food",
          "target": "café",
          "translation": "Coffee",
          "phonetic": "ka-FAY",
          "emoji": "☕",
          "example": "Je prends un café le matin.",
          "exampleTranslation": "I have a coffee in the morning.",
          "article": "le"
        },
        {
          "id": "bread",
          "theme": "food",
          "target": "pain",
          "translation": "Bread",
          "phonetic": "PANH",
          "emoji": "🍞",
          "example": "J'achète du pain à la boulangerie.",
          "exampleTranslation": "I buy bread at the bakery.",
          "article": "le"
        },
        {
          "id": "apple",
          "theme": "food",
          "target": "pomme",
          "translation": "Apple",
          "phonetic": "PUM",
          "emoji": "🍎",
          "example": "Je mange une pomme.",
          "exampleTranslation": "I eat an apple.",
          "article": "la"
        },
        {
          "id": "chicken",
          "theme": "food",
          "target": "poulet",
          "translation": "Chicken",
          "phonetic": "poo-LEH",
          "emoji": "🍗",
          "example": "Le poulet est délicieux.",
          "exampleTranslation": "The chicken is delicious.",
          "article": "le"
        },
        {
          "id": "rice",
          "theme": "food",
          "target": "riz",
          "translation": "Rice",
          "phonetic": "REE",
          "emoji": "🍚",
          "example": "Je mange du riz avec le poulet.",
          "exampleTranslation": "I eat rice with the chicken.",
          "article": "le"
        },
        {
          "id": "tea",
          "theme": "food",
          "target": "thé",
          "translation": "Tea",
          "phonetic": "TAY",
          "emoji": "🍵",
          "example": "Tu veux un thé ?",
          "exampleTranslation": "Do you want a tea?",
          "article": "le"
        },
        {
          "id": "the_bill",
          "theme": "food",
          "target": "addition",
          "translation": "The bill / check",
          "phonetic": "la-dee-see-OHN",
          "emoji": "🧾",
          "example": "L'addition, s'il vous plaît.",
          "exampleTranslation": "The check, please.",
          "article": "l'",
          "note": "Feminine: l'addition."
        },
        {
          "id": "mother",
          "theme": "family",
          "target": "mère",
          "translation": "Mother",
          "phonetic": "MEHR",
          "emoji": "👩",
          "example": "Ma mère est gentille.",
          "exampleTranslation": "My mother is kind.",
          "article": "la",
          "note": "Everyday word for 'mom': 'maman'."
        },
        {
          "id": "father",
          "theme": "family",
          "target": "père",
          "translation": "Father",
          "phonetic": "PEHR",
          "emoji": "👨",
          "example": "Mon père travaille beaucoup.",
          "exampleTranslation": "My father works a lot.",
          "article": "le",
          "note": "Everyday word for 'dad': 'papa'."
        },
        {
          "id": "friend",
          "theme": "family",
          "target": "ami",
          "translation": "Friend",
          "phonetic": "a-MEE",
          "emoji": "🤝",
          "example": "C'est mon ami.",
          "exampleTranslation": "He is my friend.",
          "article": "l'",
          "note": "Feminine: une amie."
        },
        {
          "id": "child",
          "theme": "family",
          "target": "enfant",
          "translation": "Child",
          "phonetic": "ahn-FAHN",
          "emoji": "🧒",
          "example": "L'enfant joue dans le parc.",
          "exampleTranslation": "The child plays in the park.",
          "article": "l'"
        },
        {
          "id": "man",
          "theme": "family",
          "target": "homme",
          "translation": "Man",
          "phonetic": "UM",
          "emoji": "👨",
          "example": "Cet homme est très grand.",
          "exampleTranslation": "This man is very tall.",
          "article": "l'",
          "note": "The 'h' is silent."
        },
        {
          "id": "woman",
          "theme": "family",
          "target": "femme",
          "translation": "Woman",
          "phonetic": "FAM",
          "emoji": "👩",
          "example": "Cette femme est médecin.",
          "exampleTranslation": "This woman is a doctor.",
          "article": "la",
          "note": "Irregular: 'emm' is pronounced 'am'."
        },
        {
          "id": "brother",
          "theme": "family",
          "target": "frère",
          "translation": "Brother",
          "phonetic": "FREHR",
          "emoji": "👦",
          "example": "Mon frère est plus jeune que moi.",
          "exampleTranslation": "My brother is younger than me.",
          "article": "le"
        },
        {
          "id": "sister",
          "theme": "family",
          "target": "sœur",
          "translation": "Sister",
          "phonetic": "SUHR",
          "emoji": "👧",
          "example": "J'ai une sœur.",
          "exampleTranslation": "I have a sister.",
          "article": "la"
        },
        {
          "id": "red",
          "theme": "colors",
          "target": "rouge",
          "translation": "Red",
          "phonetic": "ROOZH",
          "emoji": "🔴",
          "example": "La pomme est rouge.",
          "exampleTranslation": "The apple is red.",
          "article": ""
        },
        {
          "id": "blue",
          "theme": "colors",
          "target": "bleu",
          "translation": "Blue",
          "phonetic": "BLUH",
          "emoji": "🔵",
          "example": "Le ciel est bleu.",
          "exampleTranslation": "The sky is blue.",
          "article": "",
          "note": "Feminine: bleue."
        },
        {
          "id": "green",
          "theme": "colors",
          "target": "vert",
          "translation": "Green",
          "phonetic": "VEHR",
          "emoji": "🟢",
          "example": "L'herbe est verte.",
          "exampleTranslation": "The grass is green.",
          "article": "",
          "note": "Feminine: verte (with the 't' pronounced)."
        },
        {
          "id": "yellow",
          "theme": "colors",
          "target": "jaune",
          "translation": "Yellow",
          "phonetic": "ZHOHN",
          "emoji": "🟡",
          "example": "Le soleil est jaune.",
          "exampleTranslation": "The sun is yellow.",
          "article": ""
        },
        {
          "id": "black",
          "theme": "colors",
          "target": "noir",
          "translation": "Black",
          "phonetic": "NWAHR",
          "emoji": "⚫",
          "example": "Le chat est noir.",
          "exampleTranslation": "The cat is black.",
          "article": "",
          "note": "Feminine: noire."
        },
        {
          "id": "white",
          "theme": "colors",
          "target": "blanc",
          "translation": "White",
          "phonetic": "BLAHN",
          "emoji": "⚪",
          "example": "La neige est blanche.",
          "exampleTranslation": "The snow is white.",
          "article": "",
          "note": "Feminine: blanche."
        },
        {
          "id": "orange",
          "theme": "colors",
          "target": "orange",
          "translation": "Orange",
          "phonetic": "oh-RAHNZH",
          "emoji": "🟠",
          "example": "Ce fruit est orange.",
          "exampleTranslation": "This fruit is orange.",
          "article": "",
          "note": "Invariable as a color adjective."
        },
        {
          "id": "purple",
          "theme": "colors",
          "target": "violet",
          "translation": "Purple",
          "phonetic": "vee-oh-LEH",
          "emoji": "🟣",
          "example": "J'aime la couleur violette.",
          "exampleTranslation": "I like the color purple.",
          "article": "",
          "note": "Feminine: violette."
        },
        {
          "id": "airport",
          "theme": "travel",
          "target": "aéroport",
          "translation": "Airport",
          "phonetic": "a-ay-roh-POR",
          "emoji": "✈️",
          "example": "L'aéroport est loin du centre-ville.",
          "exampleTranslation": "The airport is far from downtown.",
          "article": "l'"
        },
        {
          "id": "hotel",
          "theme": "travel",
          "target": "hôtel",
          "translation": "Hotel",
          "phonetic": "oh-TEL",
          "emoji": "🏨",
          "example": "Notre hôtel est près de la plage.",
          "exampleTranslation": "Our hotel is near the beach.",
          "article": "l'"
        },
        {
          "id": "left",
          "theme": "travel",
          "target": "gauche",
          "translation": "Left",
          "phonetic": "GOHSH",
          "emoji": "⬅️",
          "example": "Tournez à gauche.",
          "exampleTranslation": "Turn left.",
          "article": ""
        },
        {
          "id": "right",
          "theme": "travel",
          "target": "droite",
          "translation": "Right",
          "phonetic": "DRWAHT",
          "emoji": "➡️",
          "example": "Tournez à droite après la banque.",
          "exampleTranslation": "Turn right after the bank.",
          "article": ""
        },
        {
          "id": "ticket",
          "theme": "travel",
          "target": "billet",
          "translation": "Ticket",
          "phonetic": "bee-YEH",
          "emoji": "🎫",
          "example": "J'ai acheté un billet de train.",
          "exampleTranslation": "I bought a train ticket.",
          "article": "le",
          "note": "For metro/bus a small ticket is 'un ticket'."
        },
        {
          "id": "train",
          "theme": "travel",
          "target": "train",
          "translation": "Train",
          "phonetic": "TRANH",
          "emoji": "🚆",
          "example": "Le train arrive à midi.",
          "exampleTranslation": "The train arrives at noon.",
          "article": "le"
        },
        {
          "id": "where_is",
          "theme": "travel",
          "target": "Où est... ?",
          "translation": "Where is...?",
          "phonetic": "oo EH",
          "emoji": "❓",
          "example": "Où est la gare ?",
          "exampleTranslation": "Where is the station?",
          "article": ""
        },
        {
          "id": "help",
          "theme": "travel",
          "target": "Au secours !",
          "translation": "Help!",
          "phonetic": "oh suh-KOOR",
          "emoji": "🆘",
          "example": "Au secours ! Aidez-moi !",
          "exampleTranslation": "Help! Help me!",
          "article": ""
        },
        {
          "id": "how_are_you",
          "theme": "phrases",
          "target": "Comment ça va ?",
          "translation": "How are you?",
          "phonetic": "koh-mahn sa VA",
          "emoji": "😊",
          "example": "Salut ! Comment ça va ?",
          "exampleTranslation": "Hi! How are you?",
          "article": "",
          "note": "More formal: 'Comment allez-vous ?'"
        },
        {
          "id": "my_name_is",
          "theme": "phrases",
          "target": "Je m'appelle...",
          "translation": "My name is...",
          "phonetic": "zhuh ma-PEL",
          "emoji": "📛",
          "example": "Bonjour, je m'appelle Marie.",
          "exampleTranslation": "Hello, my name is Marie.",
          "article": ""
        },
        {
          "id": "i_dont_understand",
          "theme": "phrases",
          "target": "Je ne comprends pas",
          "translation": "I don't understand",
          "phonetic": "zhuh nuh kohn-prahn PAH",
          "emoji": "😕",
          "example": "Désolé, je ne comprends pas.",
          "exampleTranslation": "Sorry, I don't understand.",
          "article": ""
        },
        {
          "id": "how_much",
          "theme": "phrases",
          "target": "C'est combien ?",
          "translation": "How much is it?",
          "phonetic": "say kohn-bee-AN",
          "emoji": "💰",
          "example": "C'est combien, ce livre ?",
          "exampleTranslation": "How much is this book?",
          "article": ""
        },
        {
          "id": "where_bathroom",
          "theme": "phrases",
          "target": "Où sont les toilettes ?",
          "translation": "Where is the bathroom?",
          "phonetic": "oo sohn lay twah-LET",
          "emoji": "🚻",
          "example": "Excusez-moi, où sont les toilettes ?",
          "exampleTranslation": "Excuse me, where is the bathroom?",
          "article": "",
          "note": "'Toilettes' is always plural in French."
        },
        {
          "id": "i_would_like",
          "theme": "phrases",
          "target": "Je voudrais...",
          "translation": "I would like...",
          "phonetic": "zhuh voo-DREH",
          "emoji": "🙋",
          "example": "Je voudrais un café, s'il vous plaît.",
          "exampleTranslation": "I would like a coffee, please.",
          "article": "",
          "note": "Polite way to order; softer than 'je veux' (I want)."
        },
        {
          "id": "see_you_later",
          "theme": "phrases",
          "target": "À plus tard",
          "translation": "See you later",
          "phonetic": "ah plew TAR",
          "emoji": "👋",
          "example": "À plus tard, à ce soir !",
          "exampleTranslation": "See you later, tonight!",
          "article": "",
          "note": "Casual short form: 'À plus !'"
        },
        {
          "id": "cheers",
          "theme": "phrases",
          "target": "Santé !",
          "translation": "Cheers!",
          "phonetic": "sahn-TAY",
          "emoji": "🥂",
          "example": "Santé, à ta santé !",
          "exampleTranslation": "Cheers, to your health!",
          "article": "",
          "note": "Literally 'health'; also heard: 'Tchin-tchin !'"
        }
      ]
    },
    "zh": {
      "language": "Mandarin",
      "code": "zh",
      "bcp47": "zh-CN",
      "flag": "🇨🇳",
      "native": "中文",
      "items": [
        {
          "id": "hello",
          "theme": "greetings",
          "target": "你好",
          "translation": "Hello",
          "phonetic": "nǐ hǎo",
          "emoji": "👋",
          "example": "你好，我叫小明。",
          "exampleTranslation": "Hello, my name is Xiao Ming.",
          "article": "",
          "note": "ni3 hao3 (tone sandhi → ni2 hao3)"
        },
        {
          "id": "goodbye",
          "theme": "greetings",
          "target": "再见",
          "translation": "Goodbye",
          "phonetic": "zài jiàn",
          "emoji": "👋",
          "example": "再见，明天见！",
          "exampleTranslation": "Goodbye, see you tomorrow!",
          "article": "",
          "note": "zai4 jian4"
        },
        {
          "id": "good_morning",
          "theme": "greetings",
          "target": "早上好",
          "translation": "Good morning",
          "phonetic": "zǎo shang hǎo",
          "emoji": "🌅",
          "example": "早上好！今天天气很好。",
          "exampleTranslation": "Good morning! The weather is nice today.",
          "article": "",
          "note": "zao3 shang5 hao3"
        },
        {
          "id": "please",
          "theme": "greetings",
          "target": "请",
          "translation": "Please",
          "phonetic": "qǐng",
          "emoji": "🙏",
          "example": "请坐。",
          "exampleTranslation": "Please sit down.",
          "article": "",
          "note": "qing3"
        },
        {
          "id": "thank_you",
          "theme": "greetings",
          "target": "谢谢",
          "translation": "Thank you",
          "phonetic": "xiè xie",
          "emoji": "🙏",
          "example": "谢谢你的帮助。",
          "exampleTranslation": "Thank you for your help.",
          "article": "",
          "note": "xie4 xie5"
        },
        {
          "id": "yes",
          "theme": "greetings",
          "target": "是的",
          "translation": "Yes",
          "phonetic": "shì de",
          "emoji": "✅",
          "example": "是的，我是学生。",
          "exampleTranslation": "Yes, I am a student.",
          "article": "",
          "note": "shi4 de5 (also 对 dui4 = 'that's right')"
        },
        {
          "id": "no",
          "theme": "greetings",
          "target": "不",
          "translation": "No",
          "phonetic": "bù",
          "emoji": "🚫",
          "example": "不，我不喜欢。",
          "exampleTranslation": "No, I don't like it.",
          "article": "",
          "note": "bu4 (becomes bu2 before a 4th-tone syllable)"
        },
        {
          "id": "excuse_me",
          "theme": "greetings",
          "target": "不好意思",
          "translation": "Excuse me",
          "phonetic": "bù hǎo yì si",
          "emoji": "🙋",
          "example": "不好意思，请问洗手间在哪里？",
          "exampleTranslation": "Excuse me, may I ask where the bathroom is?",
          "article": "",
          "note": "bu4 hao3 yi4 si5"
        },
        {
          "id": "one",
          "theme": "numbers",
          "target": "一",
          "translation": "One",
          "phonetic": "yī",
          "emoji": "1️⃣",
          "example": "我要一杯水。",
          "exampleTranslation": "I want one glass of water.",
          "article": "",
          "note": "yi1 (citation tone; sandhi to yi2/yi4 before other tones, e.g. yì bēi)"
        },
        {
          "id": "two",
          "theme": "numbers",
          "target": "二",
          "translation": "Two",
          "phonetic": "èr",
          "emoji": "2️⃣",
          "example": "二加二等于四。",
          "exampleTranslation": "Two plus two equals four.",
          "article": "",
          "note": "er4 (for two items use 两 liang3)"
        },
        {
          "id": "three",
          "theme": "numbers",
          "target": "三",
          "translation": "Three",
          "phonetic": "sān",
          "emoji": "3️⃣",
          "example": "我有三个苹果。",
          "exampleTranslation": "I have three apples.",
          "article": "",
          "note": "san1"
        },
        {
          "id": "four",
          "theme": "numbers",
          "target": "四",
          "translation": "Four",
          "phonetic": "sì",
          "emoji": "4️⃣",
          "example": "现在四点。",
          "exampleTranslation": "It's four o'clock now.",
          "article": "",
          "note": "si4"
        },
        {
          "id": "five",
          "theme": "numbers",
          "target": "五",
          "translation": "Five",
          "phonetic": "wǔ",
          "emoji": "5️⃣",
          "example": "一只手有五个手指。",
          "exampleTranslation": "A hand has five fingers.",
          "article": "",
          "note": "wu3"
        },
        {
          "id": "six",
          "theme": "numbers",
          "target": "六",
          "translation": "Six",
          "phonetic": "liù",
          "emoji": "6️⃣",
          "example": "我六点起床。",
          "exampleTranslation": "I get up at six.",
          "article": "",
          "note": "liu4"
        },
        {
          "id": "seven",
          "theme": "numbers",
          "target": "七",
          "translation": "Seven",
          "phonetic": "qī",
          "emoji": "7️⃣",
          "example": "一个星期有七天。",
          "exampleTranslation": "A week has seven days.",
          "article": "",
          "note": "qi1"
        },
        {
          "id": "eight",
          "theme": "numbers",
          "target": "八",
          "translation": "Eight",
          "phonetic": "bā",
          "emoji": "8️⃣",
          "example": "他八岁了。",
          "exampleTranslation": "He is eight years old.",
          "article": "",
          "note": "ba1"
        },
        {
          "id": "nine",
          "theme": "numbers",
          "target": "九",
          "translation": "Nine",
          "phonetic": "jiǔ",
          "emoji": "9️⃣",
          "example": "现在九点了。",
          "exampleTranslation": "It's nine o'clock now.",
          "article": "",
          "note": "jiu3"
        },
        {
          "id": "ten",
          "theme": "numbers",
          "target": "十",
          "translation": "Ten",
          "phonetic": "shí",
          "emoji": "🔟",
          "example": "这里有十个人。",
          "exampleTranslation": "There are ten people here.",
          "article": "",
          "note": "shi2"
        },
        {
          "id": "water",
          "theme": "food",
          "target": "水",
          "translation": "Water",
          "phonetic": "shuǐ",
          "emoji": "💧",
          "example": "我想喝水。",
          "exampleTranslation": "I want to drink water.",
          "article": "the",
          "note": "shui3"
        },
        {
          "id": "coffee",
          "theme": "food",
          "target": "咖啡",
          "translation": "Coffee",
          "phonetic": "kā fēi",
          "emoji": "☕",
          "example": "我每天早上喝咖啡。",
          "exampleTranslation": "I drink coffee every morning.",
          "article": "the",
          "note": "ka1 fei1"
        },
        {
          "id": "bread",
          "theme": "food",
          "target": "面包",
          "translation": "Bread",
          "phonetic": "miàn bāo",
          "emoji": "🍞",
          "example": "我早餐吃面包。",
          "exampleTranslation": "I eat bread for breakfast.",
          "article": "the",
          "note": "mian4 bao1"
        },
        {
          "id": "apple",
          "theme": "food",
          "target": "苹果",
          "translation": "Apple",
          "phonetic": "píng guǒ",
          "emoji": "🍎",
          "example": "这个苹果很甜。",
          "exampleTranslation": "This apple is very sweet.",
          "article": "the",
          "note": "ping2 guo3"
        },
        {
          "id": "chicken",
          "theme": "food",
          "target": "鸡肉",
          "translation": "Chicken",
          "phonetic": "jī ròu",
          "emoji": "🍗",
          "example": "我喜欢吃鸡肉。",
          "exampleTranslation": "I like to eat chicken.",
          "article": "the",
          "note": "ji1 rou4 (chicken meat; the animal alone is 鸡 ji1)"
        },
        {
          "id": "rice",
          "theme": "food",
          "target": "米饭",
          "translation": "Rice",
          "phonetic": "mǐ fàn",
          "emoji": "🍚",
          "example": "我想吃一碗米饭。",
          "exampleTranslation": "I want to eat a bowl of rice.",
          "article": "the",
          "note": "mi3 fan4 (cooked rice)"
        },
        {
          "id": "tea",
          "theme": "food",
          "target": "茶",
          "translation": "Tea",
          "phonetic": "chá",
          "emoji": "🍵",
          "example": "你想喝茶吗？",
          "exampleTranslation": "Do you want to drink tea?",
          "article": "the",
          "note": "cha2"
        },
        {
          "id": "the_bill",
          "theme": "food",
          "target": "买单",
          "translation": "The bill / check",
          "phonetic": "mǎi dān",
          "emoji": "🧾",
          "example": "服务员，买单！",
          "exampleTranslation": "Waiter, the check please!",
          "article": "the",
          "note": "mai3 dan1 (also 结账 jie2 zhang4)"
        },
        {
          "id": "mother",
          "theme": "family",
          "target": "妈妈",
          "translation": "Mother",
          "phonetic": "mā ma",
          "emoji": "👩",
          "example": "我妈妈很漂亮。",
          "exampleTranslation": "My mother is very pretty.",
          "article": "the",
          "note": "ma1 ma5"
        },
        {
          "id": "father",
          "theme": "family",
          "target": "爸爸",
          "translation": "Father",
          "phonetic": "bà ba",
          "emoji": "👨",
          "example": "我爸爸在工作。",
          "exampleTranslation": "My father is working.",
          "article": "the",
          "note": "ba4 ba5"
        },
        {
          "id": "friend",
          "theme": "family",
          "target": "朋友",
          "translation": "Friend",
          "phonetic": "péng you",
          "emoji": "🤝",
          "example": "他是我的好朋友。",
          "exampleTranslation": "He is my good friend.",
          "article": "the",
          "note": "peng2 you5"
        },
        {
          "id": "child",
          "theme": "family",
          "target": "孩子",
          "translation": "Child",
          "phonetic": "hái zi",
          "emoji": "🧒",
          "example": "这个孩子很可爱。",
          "exampleTranslation": "This child is very cute.",
          "article": "the",
          "note": "hai2 zi5"
        },
        {
          "id": "man",
          "theme": "family",
          "target": "男人",
          "translation": "Man",
          "phonetic": "nán rén",
          "emoji": "👨",
          "example": "那个男人是老师。",
          "exampleTranslation": "That man is a teacher.",
          "article": "the",
          "note": "nan2 ren2"
        },
        {
          "id": "woman",
          "theme": "family",
          "target": "女人",
          "translation": "Woman",
          "phonetic": "nǚ rén",
          "emoji": "👩",
          "example": "那个女人很聪明。",
          "exampleTranslation": "That woman is very smart.",
          "article": "the",
          "note": "nu:3 ren2"
        },
        {
          "id": "brother",
          "theme": "family",
          "target": "哥哥",
          "translation": "Brother",
          "phonetic": "gē ge",
          "emoji": "👦",
          "example": "我哥哥比我大三岁。",
          "exampleTranslation": "My older brother is three years older than me.",
          "article": "the",
          "note": "ge1 ge5 (older brother; younger brother = 弟弟 di4 di5)"
        },
        {
          "id": "sister",
          "theme": "family",
          "target": "姐姐",
          "translation": "Sister",
          "phonetic": "jiě jie",
          "emoji": "👧",
          "example": "我姐姐是医生。",
          "exampleTranslation": "My older sister is a doctor.",
          "article": "the",
          "note": "jie3 jie5 (older sister; younger sister = 妹妹 mei4 mei5)"
        },
        {
          "id": "red",
          "theme": "colors",
          "target": "红色",
          "translation": "Red",
          "phonetic": "hóng sè",
          "emoji": "🔴",
          "example": "我喜欢红色。",
          "exampleTranslation": "I like red.",
          "article": "",
          "note": "hong2 se4"
        },
        {
          "id": "blue",
          "theme": "colors",
          "target": "蓝色",
          "translation": "Blue",
          "phonetic": "lán sè",
          "emoji": "🔵",
          "example": "天空是蓝色的。",
          "exampleTranslation": "The sky is blue.",
          "article": "",
          "note": "lan2 se4"
        },
        {
          "id": "green",
          "theme": "colors",
          "target": "绿色",
          "translation": "Green",
          "phonetic": "lǜ sè",
          "emoji": "🟢",
          "example": "这件衣服是绿色的。",
          "exampleTranslation": "This piece of clothing is green.",
          "article": "",
          "note": "lu:4 se4"
        },
        {
          "id": "yellow",
          "theme": "colors",
          "target": "黄色",
          "translation": "Yellow",
          "phonetic": "huáng sè",
          "emoji": "🟡",
          "example": "香蕉是黄色的。",
          "exampleTranslation": "Bananas are yellow.",
          "article": "",
          "note": "huang2 se4"
        },
        {
          "id": "black",
          "theme": "colors",
          "target": "黑色",
          "translation": "Black",
          "phonetic": "hēi sè",
          "emoji": "⚫",
          "example": "他有一只黑色的猫。",
          "exampleTranslation": "He has a black cat.",
          "article": "",
          "note": "hei1 se4"
        },
        {
          "id": "white",
          "theme": "colors",
          "target": "白色",
          "translation": "White",
          "phonetic": "bái sè",
          "emoji": "⚪",
          "example": "雪是白色的。",
          "exampleTranslation": "Snow is white.",
          "article": "",
          "note": "bai2 se4"
        },
        {
          "id": "orange",
          "theme": "colors",
          "target": "橙色",
          "translation": "Orange",
          "phonetic": "chéng sè",
          "emoji": "🟠",
          "example": "橙色很好看。",
          "exampleTranslation": "Orange looks nice.",
          "article": "",
          "note": "cheng2 se4"
        },
        {
          "id": "purple",
          "theme": "colors",
          "target": "紫色",
          "translation": "Purple",
          "phonetic": "zǐ sè",
          "emoji": "🟣",
          "example": "她穿了一条紫色的裙子。",
          "exampleTranslation": "She wore a purple skirt.",
          "article": "",
          "note": "zi3 se4"
        },
        {
          "id": "airport",
          "theme": "travel",
          "target": "机场",
          "translation": "Airport",
          "phonetic": "jī chǎng",
          "emoji": "✈️",
          "example": "我们去机场吧。",
          "exampleTranslation": "Let's go to the airport.",
          "article": "the",
          "note": "ji1 chang3"
        },
        {
          "id": "hotel",
          "theme": "travel",
          "target": "酒店",
          "translation": "Hotel",
          "phonetic": "jiǔ diàn",
          "emoji": "🏨",
          "example": "酒店在车站附近。",
          "exampleTranslation": "The hotel is near the station.",
          "article": "the",
          "note": "jiu3 dian4"
        },
        {
          "id": "left",
          "theme": "travel",
          "target": "左边",
          "translation": "Left",
          "phonetic": "zuǒ bian",
          "emoji": "⬅️",
          "example": "银行在左边。",
          "exampleTranslation": "The bank is on the left.",
          "article": "",
          "note": "zuo3 bian5"
        },
        {
          "id": "right",
          "theme": "travel",
          "target": "右边",
          "translation": "Right",
          "phonetic": "yòu bian",
          "emoji": "➡️",
          "example": "超市在右边。",
          "exampleTranslation": "The supermarket is on the right.",
          "article": "",
          "note": "you4 bian5"
        },
        {
          "id": "ticket",
          "theme": "travel",
          "target": "票",
          "translation": "Ticket",
          "phonetic": "piào",
          "emoji": "🎫",
          "example": "我要买两张火车票。",
          "exampleTranslation": "I want to buy two train tickets.",
          "article": "the",
          "note": "piao4"
        },
        {
          "id": "train",
          "theme": "travel",
          "target": "火车",
          "translation": "Train",
          "phonetic": "huǒ chē",
          "emoji": "🚆",
          "example": "火车几点到？",
          "exampleTranslation": "What time does the train arrive?",
          "article": "the",
          "note": "huo3 che1"
        },
        {
          "id": "where_is",
          "theme": "travel",
          "target": "……在哪里？",
          "translation": "Where is...?",
          "phonetic": "… zài nǎ lǐ",
          "emoji": "❓",
          "example": "车站在哪里？",
          "exampleTranslation": "Where is the station?",
          "article": "",
          "note": "zai4 na3 li3 (sandhi → na2 li3); colloquial 在哪儿 zai4 nar3"
        },
        {
          "id": "help",
          "theme": "travel",
          "target": "救命",
          "translation": "Help!",
          "phonetic": "jiù mìng",
          "emoji": "🆘",
          "example": "救命！有人吗？",
          "exampleTranslation": "Help! Is anyone there?",
          "article": "",
          "note": "jiu4 ming4 (emergency shout; 'help me' = 帮帮我 bang1 bang5 wo3)"
        },
        {
          "id": "how_are_you",
          "theme": "phrases",
          "target": "你好吗？",
          "translation": "How are you?",
          "phonetic": "nǐ hǎo ma",
          "emoji": "😊",
          "example": "你好吗？我很好。",
          "exampleTranslation": "How are you? I'm fine.",
          "article": "",
          "note": "ni3 hao3 ma5 (sandhi → ni2 hao3 ma5)"
        },
        {
          "id": "my_name_is",
          "theme": "phrases",
          "target": "我叫……",
          "translation": "My name is...",
          "phonetic": "wǒ jiào …",
          "emoji": "📛",
          "example": "我叫李明。",
          "exampleTranslation": "My name is Li Ming.",
          "article": "",
          "note": "wo3 jiao4 (lit. 'I am called'); formal: 我的名字是 wo3 de5 ming2 zi5 shi4"
        },
        {
          "id": "i_dont_understand",
          "theme": "phrases",
          "target": "我听不懂",
          "translation": "I don't understand",
          "phonetic": "wǒ tīng bu dǒng",
          "emoji": "😕",
          "example": "对不起，我听不懂。",
          "exampleTranslation": "Sorry, I don't understand.",
          "article": "",
          "note": "wo3 ting1 bu5 dong3 (can't understand what's said); 我不明白 wo3 bu4 ming2 bai5 = don't grasp the idea"
        },
        {
          "id": "how_much",
          "theme": "phrases",
          "target": "多少钱？",
          "translation": "How much is it?",
          "phonetic": "duō shao qián",
          "emoji": "💰",
          "example": "这个多少钱？",
          "exampleTranslation": "How much is this?",
          "article": "",
          "note": "duo1 shao5 qian2"
        },
        {
          "id": "where_bathroom",
          "theme": "phrases",
          "target": "洗手间在哪里？",
          "translation": "Where is the bathroom?",
          "phonetic": "xǐ shǒu jiān zài nǎ lǐ",
          "emoji": "🚻",
          "example": "请问，洗手间在哪里？",
          "exampleTranslation": "Excuse me, where is the bathroom?",
          "article": "",
          "note": "xi3 shou3 jian1 zai4 na3 li3 (洗手 sandhi → xi2 shou3)"
        },
        {
          "id": "i_would_like",
          "theme": "phrases",
          "target": "我想要……",
          "translation": "I would like...",
          "phonetic": "wǒ xiǎng yào …",
          "emoji": "🙋",
          "example": "我想要一杯咖啡。",
          "exampleTranslation": "I would like a cup of coffee.",
          "article": "",
          "note": "wo3 xiang3 yao4 (sandhi → wo2 xiang3 yao4)"
        },
        {
          "id": "see_you_later",
          "theme": "phrases",
          "target": "回头见",
          "translation": "See you later",
          "phonetic": "huí tóu jiàn",
          "emoji": "👋",
          "example": "我先走了，回头见！",
          "exampleTranslation": "I'm leaving first, see you later!",
          "article": "",
          "note": "hui2 tou2 jian4 (also 待会儿见 dai1 hui4 r jian4)"
        },
        {
          "id": "cheers",
          "theme": "phrases",
          "target": "干杯",
          "translation": "Cheers!",
          "phonetic": "gān bēi",
          "emoji": "🥂",
          "example": "为我们的友谊干杯！",
          "exampleTranslation": "Cheers to our friendship!",
          "article": "",
          "note": "gan1 bei1 (lit. 'dry the glass')"
        }
      ]
    }
  }
};
